# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_feira', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=35)),
                ('longitude', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
                ('setcens', models.CharField(max_length=16)),
                ('areap', models.CharField(max_length=16)),
                ('cod_dist', models.CharField(max_length=2)),
                ('distrito', models.CharField(max_length=30)),
                ('cod_subpref', models.CharField(max_length=3)),
                ('subpref', models.CharField(max_length=30)),
                ('regiao5', models.CharField(max_length=10)),
                ('regiao8', models.CharField(max_length=10)),
                ('registro', models.CharField(max_length=7)),
                ('numero', models.CharField(max_length=14)),
                ('referencia', models.CharField(max_length=45)),
            ],
        ),
    ]
